default_context:
  project_name: 'Mimir'
  project_slug: 'mimir'
  domain_main: 'mimir.matthewshu.com'
  domain_staging: 'stag.mimir.matthewshu.com'
  docker_swarm_stack_name_main: 'mimir-matthewshu-com'
  docker_swarm_stack_name_staging: 'stag-mimir-matthewshu-com'
  secret_key: 'df122209b879856354d4801c0c2c46767df78f93f69cddfd75d237c23f8dae8c'
  first_superuser: 'daedaluscreationsco@gmail.com'
  first_superuser_password: '2110f6b46d287ce709262f38355b3ce866283c4f4e857f697ee152ea853710c5'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.mimir.matthewshu.com, https://stag.mimir.matthewshu.com, https://mimir.matthewshu.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'daedaluscreationsco@gmail.com'
  smtp_password: 'Icarusflewtooclosetothesun'
  smtp_emails_from_email: 'daedaluscreationsco@gmail.com'
  postgres_password: 'ed5cfe6d381c217e82bc410e626c4b8196aefad43672622e9160bf193f44f91b'
  pgadmin_default_user: 'daedaluscreationsco@gmail.com'
  pgadmin_default_user_password: '64f515133b9222d3323f06ea948db0f149184128bb94a4f7b3a30709a408d07d'
  traefik_constraint_tag: 'mimir.matthewshu.com'
  traefik_constraint_tag_staging: 'stag.mimir.matthewshu.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:e62f1bccade0cef9b37b601e5fb821a1891341c61b4f8985476bbc1e7b1fbb0c'
  sentry_dsn: ''
  docker_image_prefix: 'mimir'
  docker_image_backend: 'mimirbackend'
  docker_image_celeryworker: 'mimirceleryworker'
  docker_image_frontend: 'mimirfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
