"""add text and type

Revision ID: 1080292cf115
Revises: 9e4e23ce8c6d
Create Date: 2020-03-09 14:10:49.090565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1080292cf115'
down_revision = '9e4e23ce8c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('text', sa.String(), nullable=False))
    op.add_column('quote', sa.Column('type', sa.String(), nullable=False))
    op.alter_column('quote', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_quote_text'), 'quote', ['text'], unique=False)
    op.create_index(op.f('ix_quote_type'), 'quote', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_type'), table_name='quote')
    op.drop_index(op.f('ix_quote_text'), table_name='quote')
    op.alter_column('quote', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('quote', 'type')
    op.drop_column('quote', 'text')
    # ### end Alembic commands ###
