"""change relationships for user and tags

Revision ID: 2094e9ee194d
Revises: 39ce44cc5447
Create Date: 2020-03-07 22:21:10.509935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2094e9ee194d'
down_revision = '39ce44cc5447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
