"""rename relationship

Revision ID: 2ef950e658f9
Revises: 6dcdfe9dbe1a
Create Date: 2020-03-07 20:52:05.577973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef950e658f9'
down_revision = '6dcdfe9dbe1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'public')
    # ### end Alembic commands ###
