"""change association object to table

Revision ID: 9e4e23ce8c6d
Revises: 2094e9ee194d
Create Date: 2020-03-08 00:11:26.931102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4e23ce8c6d'
down_revision = '2094e9ee194d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
